default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 500
  username: root
  password: 1234
  host: localhost

development:
  <<: *default
  database: project_stud

production:
  <<: *default
  database: project_stud
