# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1377fda232e2ab13fefba1748d16314973c748c5d2a6a9ce2bb2144470040e6c5e6383cbff7799a128b612aee0929136d2e9b1a100b895cb6e34b919106fa62

test:
  secret_key_base: 6ca421baa6761f38293fb514243890dd7886cad7daa170166024d7440690a708c1d770a4ed67a07ff4d130465ed8d3f8621e6da4b202e4cca19d3db008580f55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
